(define
  (domain taskAssigment)
  (:requirements :adl)
  (:predicates
    (SoftwareAgent ?x )
    (DesignAgent ?x )
    (Designer ?x )
    (Engineer ?x )
    (TestingAgent ?x )
    (Employee ?x )
    (TaskAgent ?x )
    (SpecificationsAgent ?x )
    (MaterialsAgent ?x )
    (CodingAgent ?x )
    (InformaticEngineer ?x )
    (ElectronicEngineer ?x )
    (FullName ?x )
    (MaterialsEngineer ?x )
    (Developer ?x )
    (ElectronicsAgent ?x )
    (hasPersonalInfo ?x ?y )
    (CheckConsistency)
    (Error)
  )
  (:action hireElectronicEng
    :parameters ( ?n )
    :precondition ( and
      (not (CheckConsistency))
      (not (Error))
      (= b b)
    )
    :effect ( and
      (CheckConsistency)
      (when
        (not
          (exists ( ?x1 ?x2 )
            (and
              (ElectronicEngineer ?x1)
              (not
                (=?x1 ?x2 )
              )
              (ElectronicEngineer ?x2)
            )
          )
        )
        (and
          (ElectronicEngineer ?n)
        )
      )
    )
  )
  (:action CheckConsistencyAction
    :parameters ( )
    :precondition ( and
      (CheckConsistency)
      (not (Error))
    )
    :effect ( and
      (not (CheckConsistency))
      (when
        (or
          (exists (?x_2 ?_0 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (CodingAgent ?x_2)
            )
          )
          (exists (?x_2 )
            (and
              (FullName ?x_2)
              (ElectronicsAgent ?x_2)
            )
          )
          (exists (?x_2 )
            (and
              (FullName ?x_2)
              (TaskAgent ?x_2)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (TestingAgent ?x_2)
            )
          )
          (exists (?x_4 )
            (and
              (SpecificationsAgent ?x_4)
              (MaterialsEngineer ?x_4)
            )
          )
          (exists (?x_2 )
            (and
              (FullName ?x_2)
              (Designer ?x_2)
            )
          )
          (exists (?x_2 )
            (and
              (FullName ?x_2)
              (DesignAgent ?x_2)
            )
          )
          (exists (?x_5 )
            (and
              (Designer ?x_5)
              (ElectronicsAgent ?x_5)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (InformaticEngineer ?x_2)
              (hasPersonalInfo ?_0 ?x_2)
            )
          )
          (exists (?x_2 )
            (and
              (FullName ?x_2)
              (ElectronicEngineer ?x_2)
            )
          )
          (exists (?x_0 )
            (and
              (ElectronicsAgent ?x_0)
              (MaterialsEngineer ?x_0)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (Engineer ?x_2)
              (hasPersonalInfo ?_0 ?x_2)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (SoftwareAgent ?x_2)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (MaterialsAgent ?x_2)
            )
          )
          (exists (?x_6 )
            (and
              (Designer ?x_6)
              (SoftwareAgent ?x_6)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (SpecificationsAgent ?x_2)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (ElectronicsAgent ?x_2)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (FullName ?x_2)
              (hasPersonalInfo ?x_2 ?_0)
            )
          )
          (exists (?x_4 )
            (and
              (CodingAgent ?x_4)
              (MaterialsEngineer ?x_4)
            )
          )
          (exists (?x_2 )
            (and
              (InformaticEngineer ?x_2)
              (FullName ?x_2)
            )
          )
          (exists (?x_1 )
            (and
              (InformaticEngineer ?x_1)
              (ElectronicsAgent ?x_1)
            )
          )
          (exists (?_0 ?_1 )
            (hasPersonalInfo ?_0 ?_1)
          )
          (exists (?x_2 ?_0 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (Developer ?x_2)
            )
          )
          (exists (?x_2 )
            (and
              (FullName ?x_2)
              (TestingAgent ?x_2)
            )
          )
          (exists (?x_3 )
            (and
              (SpecificationsAgent ?x_3)
              (Developer ?x_3)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (ElectronicEngineer ?x_2)
            )
          )
          (exists (?x_2 )
            (and
              (FullName ?x_2)
              (SpecificationsAgent ?x_2)
            )
          )
          (exists (?x_2 )
            (and
              (FullName ?x_2)
              (SoftwareAgent ?x_2)
            )
          )
          (exists (?x_6 )
            (and
              (Designer ?x_6)
              (SpecificationsAgent ?x_6)
            )
          )
          (exists (?x_2 )
            (and
              (FullName ?x_2)
              (CodingAgent ?x_2)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (Designer ?x_2)
            )
          )
          (exists (?x_7 )
            (and
              (ElectronicEngineer ?x_7)
              (CodingAgent ?x_7)
            )
          )
          (exists (?x_2 ?_0 ?_1 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (hasPersonalInfo ?x_2 ?_1)
            )
          )
          (exists (?x_2 )
            (and
              (Engineer ?x_2)
              (FullName ?x_2)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (Employee ?x_2)
              (hasPersonalInfo ?_0 ?x_2)
            )
          )
          (exists (?x_6 )
            (and
              (CodingAgent ?x_6)
              (Designer ?x_6)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (DesignAgent ?x_2)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (TaskAgent ?x_2)
            )
          )
          (exists (?x_2 ?_0 )
            (and
              (hasPersonalInfo ?_0 ?x_2)
              (MaterialsEngineer ?x_2)
            )
          )
          (exists (?x_2 )
            (and
              (FullName ?x_2)
              (Developer ?x_2)
            )
          )
          (exists (?x_2 )
            (and
              (FullName ?x_2)
              (MaterialsEngineer ?x_2)
            )
          )
          (exists (?x_2 )
            (and
              (FullName ?x_2)
              (MaterialsAgent ?x_2)
            )
          )
          (exists (?x_2 )
            (and
              (Employee ?x_2)
              (FullName ?x_2)
            )
          )
          (exists (?x_4 )
            (and
              (MaterialsEngineer ?x_4)
              (SoftwareAgent ?x_4)
            )
          )
        )
        (Error)
      )
    )
  )
)